runtime: php81 
env: standard
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
handlers:
  - url: /static
    static_dir: static
  - url: /(.*\.(css|js|png|jpg|ico|ttf|woff))
    static_files: \1
    upload: (.*\.(css|js|png|jpg|ico|ttf|woff))
  - url: /
    static_files: index.html
    upload: index.html
  - url: /single.html
    static_files: single.html
    upload: single.html
  - url: /category1
    static_files: catpage1.html
    upload: catpage1.html